version: '3.7'  # Docker Compose file format version

services:
  samba:
    container_name: samba
    hostname: samba
    build: ./samba/  # Builds an image from the Dockerfile
    ports:
      - "1390:139"
      - "4450:445"
    volumes:
      - samba_volume:/mount/shares
    environment:
      - TZ=Europe/Zurich
      - SAMBA_USERS=${SAMBA_USERS}
      - CREATE_USER_SHARES=true
      - BASE_DIR=/mount/shares
    networks:
      - internal_network
      - external_network
    restart: always

  tomcat:
    container_name: tomcat
    hostname: tomcat
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - tomcat_volume:/usr/local/tomcat/webapps
      - ./tomcat/index.html:/usr/local/tomcat/webapps/ROOT/index.html  # Custom landing page
    networks:
      - internal_network
      - external_network
    restart: always

  jupyter:
    container_name: jupyter
    hostname: jupyter
    image: quay.io/jupyter/scipy-notebook
    ports:
      - "8888:8888"
    networks:
      - internal_network
      - external_network
    volumes:
      - jupyter_volume:/home/jovyan/work
    restart: always

networks:
  internal_network:
    driver: bridge
    internal: true  # Internal network, not exposed externally
  external_network:
    driver: bridge  # External network, for accessing services from outside

volumes:
  samba_volume:
    driver: local  # Stores Samba shares data
  tomcat_volume:
    driver: local  # Stores Tomcat stuff
  jupyter_volume:
    driver: local  # Stores Jupyter notebooks
